Gamayun.UI/Areas/Student/Controllers/SectionController.cs
using Gamayun.Identity;
using Gamayun.Infrastucture;
using Gamayun.Infrastucture.Command;
using Gamayun.Infrastucture.Grid;
using Gamayun.Infrastucture.Grid.ResultModels;
using Gamayun.Infrastucture.Query;
using Gamayun.Infrastucture.Query.Student;
using Gamayun.UI.Controllers;
using Gamayun.UI.Utilities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper.QueryableExtensions;
using AutoMapper;
using Gamayun.Infrastucture.Entities;
using Gamayun.UI.Areas.Student.Models;

namespace Gamayun.UI.Areas.Student.Controllers
{
    public class SectionController : StudentController
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly GamayunDbContext _dbContext;
        private readonly MapperConfiguration _mapperConfiguration;

        public SectionController(
        UserManager<AppUser> userManager,
        GamayunDbContext dbContext,
        MapperConfiguration mapperConfiguration,
        ICommandRunner commandRunner,
        IGridQueryRunner gridQueryRunner,
        ISettings settings)
        : base(commandRunner, gridQueryRunner, settings)
        {
            _userManager = userManager;
            _dbContext = dbContext;
            _mapperConfiguration = mapperConfiguration;
        }

        public ViewResult FindSections()
            => View(new GridConfiguration<SectionRM>
            {
                DataUrl = GetActionUrl(nameof(FindSectionsQuery)),
            });

        [HttpPost]
        public JsonResult FindSectionsQuery([FromBody]GridFilters<SectionRM> filter)
            => Json(_gridQueryRunner.Run(filter, new FindSectionsQueryHandler.Query 
            {
                StudentId = GetStudentId().Result ?? -1
            }));


        public ActionResult MySections()
            => View(new GridConfiguration<SectionRM>
            {
                DataUrl = GetActionUrl(nameof(MySectionsQuery)),
                SelectHref = GetActionUrl(nameof(SectionView))
            });

        [HttpPost]
        public JsonResult MySectionsQuery([FromBody]GridFilters<SectionRM> filter)
                  => Json(_gridQueryRunner.Run(filter, new MySectionsQueryHandler.Query
                  {
                      StudentId = GetStudentId().Result ?? -1
                  }));

        public async  Task<ActionResult> SectionView(int id)
        {
            var studentId = await GetStudentId();
            if (studentId == null)
                return Error();

            var vm = _dbContext.Sections
                .Include(x => x.StudentSections)
                .Where(x => x.StudentSections.Any(y => y.StudentID == studentId))
                .ProjectTo<StudentSectionVm>(_mapperConfiguration).FirstOrDefault(x => x.Id == id);
            if (vm == null)
                return Error();

            return View(vm);
        }

        [HttpPost]
        public async Task<ActionResult> SignIn(SignInOutDTO dto)
        {
            var studentId = await GetStudentId();
            if (studentId == null)
                return Error();

            var section = _dbContext.Sections
                .Include(x => x.StudentSections)
                .FirstOrDefault(x => x.ID == dto.Id);

            if (section == null || section.State != SectionState.Active) 
                return Error();

            if (_dbContext.StudentSections.Any(x => x.StudentID == studentId && x.SectionID == dto.Id))
                return Error();

            _dbContext.StudentSections.Add(new StudentSection
            {
                SectionID = dto.Id,
                StudentID = studentId.Value
            });

            _dbContext.SaveChanges();

            return RedirectToAction(nameof(SectionView), new { id = dto.Id });
        }

        [HttpPost]
        public async Task<ActionResult> SignOut(SignInOutDTO dto)
        {
            var studentId = await GetStudentId();
            if (studentId == null)
                return Error();
            var studentSection = _dbContext.StudentSections
                .Where(x => x.SectionID == dto.Id)
                .Where(x => x.StudentID == studentId)
                .FirstOrDefault();
            
            if (studentSection == null)
                return Error();

            _dbContext.Entry(studentSection).State = EntityState.Deleted;
            _dbContext.SaveChanges();

            return RedirectToAction(nameof(FindSections));
        }

        private async Task<int?> GetStudentId()
        {
            var user = await _userManager.GetUserAsync(User);
            return _dbContext.Students.FirstOrDefault(x => x.AppUserID == user.Id)?.ID;
        }

    }
}

Gamayun.UI/Areas/Teacher/Controllers/SectionController.cs
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Gamayun.Identity;
using Gamayun.Infrastucture;
using Gamayun.Infrastucture.Command;
using Gamayun.Infrastucture.Command.Teacher;
using Gamayun.Infrastucture.Grid;
using Gamayun.Infrastucture.Grid.ResultModels;
using Gamayun.Infrastucture.Query;
using Gamayun.Infrastucture.Query.Admin;
using Gamayun.Infrastucture.Query.Teacher;
using Gamayun.UI.Areas.Teacher.Models;
using Gamayun.UI.Controllers;
using Gamayun.UI.Utilities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace Gamayun.UI.Areas.Teacher.Controllers
{
    public class SectionController : TeacherController
    {
        private readonly MapperConfiguration _mapperConfiguration;

        public SectionController(
        GamayunDbContext dbContext,
        MapperConfiguration mapperConfiguration,
        UserManager<AppUser>
        userManager,
        ICommandRunner commandRunner,
        IGridQueryRunner gridQueryRunner,
        ISettings settings)
        : base(dbContext, userManager, commandRunner, gridQueryRunner, settings)
        {
            _mapperConfiguration = mapperConfiguration;
        }

        public ActionResult SectionView(int id)
        {

            var vm = _dbContext.Sections
                .ProjectTo<SectionVm>(_mapperConfiguration)
                .FirstOrDefault(x => x.Id == id);
            if (vm == null)
            {
                return ErrorResult();
            }
            var section = _dbContext.Sections
                .Include(x => x.PresenceDates)
                    .ThenInclude(x => x.Presences)
                        .ThenInclude(x => x.Student)
                            .ThenInclude(x => x.AppUser)
                .FirstOrDefault(x => x.ID == vm.Id);

            var studentGroupedPresences = section.PresenceDates.SelectMany(x => x.Presences.Select(y => new
            {
                Date = x.Date,
                DateId = x.ID,
                StudentId = y.StudentID,
                Student = y.Student.AppUser.FullName,
                WasPresent = y.WasPresent
            })).GroupBy(x => x.StudentId).ToList();

            var presencesVm = studentGroupedPresences.Select(x =>
            {
                var studentData = x.Select(z => new { z.Student, z.StudentId }).FirstOrDefault();
                return new PresenceVm
                {
                    Student = studentData.Student,
                    StudentId = studentData.StudentId ?? 0,
                    StudentPresences = x.Select(y => (y.WasPresent, y.DateId)).ToList(),
                };
            }).OrderBy(x => x.Student);

            List<(string date, int presenceDateId)> datesVm = section.PresenceDates
                .OrderBy(x => x.Date)
                .Select(x => (x.Date.ToString("dd MMMM yyyy"), x.ID))
                .ToList();


            vm.Presences = presencesVm;
            vm.Dates = datesVm;

            return View(vm);
        }

        public ViewResult SectionCreate()
            => View(new SectionCreateVm
            {
                TopicGridConfiguration = new GridConfiguration<TopicRM>
                {
                    DataUrl = this.GetActionUrl<TopicController>(nameof(TopicController.TopicSearchQuery)),
                    PageSize = 3,
                },
                SemesterGridConfiguration = new GridConfiguration<SemesterRM>
                {
                    DataUrl = this.GetActionUrl(nameof(SemesterSearchQuery)),
                    PageSize = 3,
                },
                StudentGridConfiguration= new GridConfiguration<UserRM>
                {
                    DataUrl = this.GetActionUrl(nameof(StudentSearchQuery)),
                    PageSize = 3,
                },
            });
        [HttpPost]
        public ActionResult SectionCreate(CreateSectionCommandHandler.Command command)
        {
            var result = _commandRunner.Run(command);
            if (result.Succeeded)
            {
                return RedirectToAction(nameof(SectionSearch));
            }

            ViewBag.Errors = result.Errors;
            return View();
        }
        public ActionResult SectionEdit(int id)
        {
            var vm = _dbContext.Sections
                .Include(x=>x.StudentSections)
                .ThenInclude(y=>y.Student)
                .ThenInclude(z=>z.AppUser)
                .Select(x =>
            new SectionEditVm
            {
                Id = x.ID,
                Name = x.Name,
                State = x.State,
                Students = x.StudentSections.Select(y => new SectionStudentVm { Id = y.StudentID, Name = y.Student.AppUser.FullName }),
            }).FirstOrDefault(x => x.Id == id);
            if (vm == null)
            {
                return ErrorResult();
            }

            vm.StudentsGridConfiguration = new GridConfiguration<UserRM>
            {
                DataUrl = GetActionUrl(nameof(StudentSearchQuery)),
            };
            return View(vm);
        }

        [HttpPost]
        public ActionResult SectionEdit(SectionEditDTO dto)
        {
            var command = new EditSectionCommandHandler.Command
            {
                Id = dto.Id,
                Name = dto.Name,
                State = dto.State,
                StudentIds = string.IsNullOrWhiteSpace(dto.StudentIds) 
                ? new List<int>() 
                : dto.StudentIds.Split(',').Select(x => int.Parse(x)).ToList(),
            };

            var result = _commandRunner.Run(command);
            if (result.Succeeded)
            {
                return RedirectToAction(nameof(SectionSearch));
            }

            ViewBag.Errors = result.Errors;
            return View();
        }

        public ViewResult SectionSearch()
             => View(new GridConfiguration<SectionRM>
             {
                 DataUrl = GetActionUrl(nameof(SectionSearchQuery)),
                 SelectHref = GetActionUrl(nameof(SectionView))
             });
        [HttpPost]
        public async Task<JsonResult> SectionSearchQuery([FromBody]GridFilters<SectionRM> filter)
            => Json(_gridQueryRunner.Run(filter, new SectionsQueryHandler.Query
            {
                TeacherID = await GetTeacherId() ?? 0
            }));
        [HttpPost]
        public JsonResult SemesterSearchQuery([FromBody]GridFilters<SemesterRM> filters)
        => Json(_gridQueryRunner.Run(filters, new SemestersQueryHandler.Query()));

        [HttpPost]
        public JsonResult StudentSearchQuery([FromBody]GridFilters<UserRM> filters)
       => Json(_gridQueryRunner.Run(filters, new StudentsForSectionQueryHandler.Query()));

        [HttpPost]
        public ActionResult UpdatePresences(string data, int sectionId)// data = [studentId:dateId:wasPresent]
        {
            var regex = new Regex(@"(\d):(\d):(false|true)", RegexOptions.IgnoreCase);
            (int studentId, int dateId, bool wasPresent)[] tuple = data.Split(',').Select(x => {
                var groups = regex.Match(x).Groups;
                return
                    (int.Parse(groups[1].Value),
                    int.Parse(groups[2].Value),
                    bool.Parse(groups[3].Value.ToLower()));
                }).ToArray();

            var result = _commandRunner.Run(new UpdateSectionPresencesCommandHandler.Command(tuple, sectionId));

            if (result.Succeeded)
            {
                return RedirectToAction(nameof(SectionView), new { id = sectionId });
            }

            return Error();
        }

        [HttpPost]
        public ActionResult ChangeGrade(SectionGradeDTO dto)
        {
            var section = _dbContext.Sections.FirstOrDefault(x => x.ID == dto.Id);
            if (section == null || dto.Grade == null 
                || dto.Grade < 2 || dto.Grade > 5)
            {
                return Error();
            }

            section.Grade = dto.Grade;
            _dbContext.SaveChanges();

            return RedirectToAction(nameof(SectionView), new { id = dto.Id });

        }
    }
}

Gamayun.UI/Areas/Teacher/Views/Section/SectionCreate.cshtml
@using Gamayun.Infrastucture.Grid.ResultModels
@model SectionCreateVm
@{
    var topicGridConfiguration = Model.TopicGridConfiguration;
    topicGridConfiguration.Actions.Add(new GridAction
    {
        JsFunction = "sectionCreate.topicAction",
        Title = "Choose"
    });

    var semesterGridConfiguration = Model.SemesterGridConfiguration;
    semesterGridConfiguration.Actions.Add(new GridAction
    {
        JsFunction = "sectionCreate.semesterAction",
        Title = "Choose"
    });

    var studentGridConfiguration = Model.StudentGridConfiguration;
    studentGridConfiguration.Actions.Add(new GridAction
    {
        JsFunction = "sectionCreate.studentAction",
        Title = "Add"
    });

    ViewData["Title"] = "Create Section";
    var errors = ViewBag.Errors ?? Array.Empty<string>();
}
<script src="~/js/Teacher/Section/Gamayun.Section.Create.js"></script>
<script>
    var sectionCreate = new GamayunSectionCreate();
</script>

@await Html.PartialAsync("_PageHeader", "Section Create Page")

<hr />
<div class="row">
    <div class="col-xl-6">
        <h2><strong>Available Topics:</strong></h2>
        @await Html.PartialAsync("_Grid", topicGridConfiguration)
    </div>
    <div class="col-xl-6">
        <h2><strong>Available Semesters:</strong></h2>
        @await Html.PartialAsync("_Grid", semesterGridConfiguration)
    </div>
</div>
<hr />
<div class="row">
    <div class="col-xl-12">
        <h2><strong>All students:</strong></h2>
        @await Html.PartialAsync("_Grid", studentGridConfiguration)
    </div>
</div>
<hr />
<div class="container-fluid">
    <div class="jumbotron">
        @foreach (var error in errors)
        {
            <div class="alert alert-danger" role="alert">
                <strong>@error</strong>
            </div>
        }
        <form asp-area="Teacher" asp-controller="Section" asp-action="SectionCreate">
            <div class="row">
                <div class="col-xl-6 form-group">
                    <label for="name">Name</label>
                    <input id="name" name="name" class="form-control" placeholder="Name" required>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-6 form-group">
                    <label for="name">Topic</label>
                    <input id="topicName" class="form-control" placeholder="Choose Topic" disabled required>
                    <input hidden id="topicId" name="topicId" />
                </div>
                <div class="col-xl-6 form-group">
                    <label for="name">Semester</label>
                    <input id="semesterName" class="form-control" placeholder="Choose Semester" disabled required>
                    <input hidden id="semesterId" name="semesterId" />
                </div>
            </div>
            <div class="row">
                <div class="col-xl-6">
                    <h2><strong>Picked students:</strong></h2>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Student</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody id="student-container">
                        </tbody>
                    </table>
                </div>
                <div class="col-xl-6 form-group">
                    <h2><strong>Presence dates:</strong></h2>
                    <input id="presence-selector" class="form-control-sm" readonly/>
                    <button type="button" style="margin-left:1em;" class="btn btn-primary" id="add-presence">Add</button>
                    <button type="button" style="margin-left:1em;" class="btn btn-danger" id="reset-presence">Reset</button>
                    <ul id="presence-container" class="list-group">
                    </ul>
                </div>
            </div>
            
            <input hidden name="students" />
            <input hidden name="presences" />
            <div class="container-controls">
                <button id="create-section" class="btn btn-primary" disabled>Create</button>
            </div>
        </form>
    </div>
</div>

<script>
    var presences = [];
    $("#presence-selector").datepicker();
    $("#add-presence").click(function () {
        var date = $("#presence-selector").val();
        if (!isNaN(Date.parse(date))) {
            presences.push(date);
            $("#presence-container").append($("<li class='list-group-item'><strong>" + date + "</strong></li>"));
            $("[name='presences']").val(presences.toString());
            $("#presence-selector").val("");
        }
    });

    $("#reset-presence").click(function () {
        presences = [];
        $("#presence-container").text("");
        $("[name='presences']").val(presences.toString());
    });
</script>

Gamayun.UI/Areas/Teacher/Views/Section/SectionEdit.cshtml
@using Gamayun.Infrastucture.Entities
@model SectionEditVm
@{
    ViewData["Title"] = "Edit Section";
    var errors = ViewBag.Errors ?? Array.Empty<string>();
     var studentGridConfiguration = Model.StudentsGridConfiguration;
    studentGridConfiguration.Actions.Add(new GridAction
    {
        JsFunction = "studentAction",
        Title = "Add"
    });
}

@await Html.PartialAsync("_PageHeader", "Section Edit Page")

<hr />
<div class="container-fluid">
    <div class="jumbotron">
        @foreach (var error in errors)
        {
            <div class="alert alert-danger" role="alert">
                <strong>@error</strong>
            </div>
        }
        <div class="row">
            <div class="col-xl-6">
                 <h2><strong>All students:</strong></h2>
                 @await Html.PartialAsync("_Grid", studentGridConfiguration)
            </div>
            <div class="col-xl-6">
                 <h2><strong>Picked students:</strong></h2>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Student</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody id="student-container">
                            @foreach (var item in Model.Students)
                            {
                                <tr class="predefined-student" id='@($"{item.Id}")'>
                                    <td>@item.Name<td>
                                    <td><button type='button' class='btn btn-danger'>Remove</button></td>
                                </tr>
                            }
                        </tbody>
                    </table>
            </div>
        </div>
        <form id="edit-form" asp-area="Teacher" asp-controller="Section" asp-action="SectionEdit">
            <input hidden asp-for="Id" />
            <input hidden name="studentIds" />
            <div class="row">
                <div class="col-lg-6 form-group">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Name" required>
                </div>
                <div class="col-lg-6 form-group">
                    <label asp-for="State">Section State</label>
                    <select asp-for="State" class="form-control" asp-items="Html.GetEnumSelectList<SectionState>()"></select>
                </div>
            </div>
            <div class="container-controls">
                <button class="btn btn-primary">Save</button>
            </div>
        </form>
    </div>
</div>
<script>
    debugger;
    $(".predefined-student").each(function (index, elem) {
        $(elem).find("button").click(function () {
            var studentId = +$(elem).prop("id")
            students = students.filter(x => x !== studentId);
            $("#" + studentId).remove();
        })
    })

    var students = [@(String.Join(", ", Model.Students.Select(x=>x.Id)))];
    var studentAction = function (item) {
        var studentId = item.id
        if ($.inArray(studentId, students) != -1) {
            return;
        }

        students.push(studentId);
        var rowId = "row_" + item.id;
        var row = $("<tr id='" + rowId + "'>" + "<td>" + item.firstName + " " + item.lastName + "<td><td><button type='button' class='btn btn-danger'>Remove</button></td>" + "</tr>");
        $("#student-container").append(row);

        $("#" + rowId + " button").click(function () {
            students = students.filter(x => x !== studentId);
            $("#" + rowId).remove();
        })
    }

    $("#edit-form").submit(function () {
        $('[name="studentIds"]').val(students.toString());
    })


</script>

Gamayun.UI/Areas/Teacher/Views/Section/SectionSearch.cshtml
@model IGridConfiguration
@{ 
    ViewData["Title"] = "Search Section";
}
@await Html.PartialAsync("_PageHeader", "Section Search Page")

@await Html.PartialAsync("_Grid", Model)

Gamayun.UI/Areas/Teacher/Views/Section/SectionView.cshtml
@model SectionVm
@{
    ViewData["Title"] = "View Semester";
}
@await Html.PartialAsync("_PageHeader", "Section View Page")

<hr />
<div class="container-fluid">
    <div class="jumbotron">
        <p><strong>Name:</strong>&nbsp;@Model.Name</p>
        <p><strong>Status:</strong>&nbsp;@Model.Status</p>
        <p><strong>Topic Name:</strong>&nbsp;@Model.TopicName</p>
        <form id="grade-form" method="post" asp-action="ChangeGrade" asp-controller="Section">
            <input hidden asp-for="Id" />
            <div class="form-group">
                <strong>Section Grade:</strong>&nbsp;
                <input style="width:initial; display:inline-block;" class="form-control" type="number" name="grade" min="2" value="@Model.Grade" max="5" step="1" />
                <button class="btn btn-primary" disabled>Save</button>
            </div>
        </form>

        <table id="presence-picker" class="table table-striped">
            <thead>
                <tr>
                    <th>Student</th>
                    @foreach (var dateVm in Model.Dates)
                    {
                        <th>@dateVm.date</th>
                    }
                </tr>
            </thead>
            <tbody>

                @foreach (var presenceData in Model.Presences)
                {
                    <tr>
                        <td>@presenceData.Student</td>
                        @foreach (var pres in presenceData.StudentPresences)
                        {
                            <td class="data-cell">
                                <input class="big-checkbox was-present" type="checkbox" @(pres.wasPresent ? "checked" : "")>
                                <input hidden class="date-id" value="@pres.presenceDateId" />
                                <input hidden class="student-id" value="@presenceData.StudentId" />
                                
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>

        <form id="presence-form" method="post" asp-action="UpdatePresences" asp-controller="Section">
            <input name="data" hidden />
            <input name="sectionId" value="@Model.Id" hidden />
            <button class="btn btn-primary" disabled>Save</button>
        </form>



        <div class="container-controls">
            <a asp-action="SectionEdit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
        </div>
    </div>
</div>
<script>
    $('.was-present').click(function(){
        $('#presence-form button').prop("disabled", false)
    })
    $('#presence-form').submit(function () {
        var dataCells = $("#presence-picker .data-cell");
        var formInput = $('#presence-form input[name="data"]');
        var data = [];
        dataCells.each(function (index, elem) {
            var wasPresent = $(elem).find(".was-present").get(0).checked;
            var dateId = $(elem).find(".date-id").val();
            var studentId = $(elem).find(".student-id").val();
            
            data.push("[" + studentId + ":" + dateId + ":" + wasPresent + "]");
        });

        formInput.val(data.toString());
    });

    var gradeForm = $('#grade-form');
    gradeForm.find('input').change(function () {
        gradeForm.find('button').prop('disabled', false);
    })
</script>