Gamayun.UI/Areas/Admin/Controllers/SemesterController.cs
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Gamayun.Infrastucture;
using Gamayun.Infrastucture.Command;
using Gamayun.Infrastucture.Command.Admin;
using Gamayun.Infrastucture.Grid;
using Gamayun.Infrastucture.Grid.ResultModels;
using Gamayun.Infrastucture.Query;
using Gamayun.Infrastucture.Query.Admin;
using Gamayun.UI.Areas.Admin.Models;
using Gamayun.UI.Controllers;
using Gamayun.UI.Utilities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Gamayun.UI.Areas.Admin.Controllers
{
    public class SemesterController : AdminController
    {
        private readonly GamayunDbContext _dbContext;
        private readonly MapperConfiguration _mapperConfiguration;

        public SemesterController(
            GamayunDbContext dbContext,
            MapperConfiguration mapperConfiguration,
            ICommandRunner commandRunner, 
            IGridQueryRunner gridQueryRunner, 
            ISettings settings)
            : base(commandRunner, gridQueryRunner, settings)
        {
            _dbContext = dbContext;
            _mapperConfiguration = mapperConfiguration;
        }
        public ActionResult SemesterView(int id)
        {
            var vm = _dbContext.Semesters
                .ProjectTo<SemesterVm>(_mapperConfiguration)
                .FirstOrDefault(x => x.ID == id);
            
            if (vm == null)
            {
                return ErrorResult();
            }
            return View(vm);
        }

        public ViewResult SemesterCreate() => View();
        [HttpPost]
        public ActionResult SemesterCreate(CreateSemesterCommandHandler.Command command)
        {
            var result = _commandRunner.Run(command);
            if (result.Succeeded)
            {
                return RedirectToAction(nameof(SemesterSearch));
            }

            ViewBag.Errors = result.Errors;
            return View();
        }

        public ActionResult SemesterEdit(int id)
        {
            var vm = _dbContext.Semesters.Select(x =>
            new EditSemesterCommandHandler.Command
            {
                ID = x.ID,
                Major = x.Major,
                FinishedOn = x.FinishedOn
            }).FirstOrDefault(x => x.ID == id);
            if (vm == null)
            {
                return ErrorResult();
            }
            return View(vm);
        }
        
        [HttpPost]
        public ActionResult SemesterEdit(EditSemesterCommandHandler.Command command)
        {
            var result = _commandRunner.Run(command);
            if (result.Succeeded)
            {
                return RedirectToAction(nameof(SemesterSearch));
            }

            ViewBag.Errors = result.Errors;
            return View();
        }

        public ViewResult SemesterSearch()
             => View(new GridConfiguration<SemesterRM>
             {
                 DataUrl = GetActionUrl(nameof(SemesterSearchQuery)),
                 SelectHref = GetActionUrl(nameof(SemesterView))
             });

        [HttpPost]
        public JsonResult SemesterSearchQuery([FromBody]GridFilters<SemesterRM> filter)
            => Json(_gridQueryRunner.Run(filter, new SemestersQueryHandler.Query()));

        [HttpPost]
        public ActionResult SemesterObsolete(int id)
        {
            var semester = _dbContext.Semesters.FirstOrDefault(x => x.ID == id);
            if (semester == null)
            {
                return ErrorResult();
            }
            semester.IsObsolete = true;
            _dbContext.SaveChanges();

            return RedirectToAction(nameof(SemesterView), new { id });
        }

        [HttpPost]
        public ActionResult SemesterRestore(int id)
        {
            var semester = _dbContext.Semesters.FirstOrDefault(x => x.ID == id);
            if (semester == null)
            {
                return ErrorResult();
            }
            semester.IsObsolete = false;
            _dbContext.SaveChanges();

            return RedirectToAction(nameof(SemesterView), new { id });
        }
    }
}

Gamayun.UI/Areas/Admin/Views/Semester/SemesterCreate.cshtml
@using Gamayun.Infrastucture.Command.Admin
@model CreateSemesterCommandHandler.Command
@{
    ViewData["Title"] = "Create Semester";
    var errors = ViewBag.Errors ?? Array.Empty<string>();
}

@await Html.PartialAsync("_PageHeader", "Semester Create Page")

<hr />
<div class="container-fluid">
    <div class="jumbotron">
        @foreach (var error in errors)
        {
            <div class="alert alert-danger" role="alert">
                <strong>@error</strong>
            </div>
        }
        <form asp-area="Admin" asp-controller="Semester" asp-action="SemesterCreate">
            <div class="row">
                <div class="col-lg-6 form-group">
                    <label asp-for="Major">Major</label>
                    <input asp-for="Major" class="form-control" placeholder="Major" required>
                </div>
                <div class="col-lg-6 form-group">
                    <label asp-for="FinishedOn">Finished On</label>
                    <input asp-for="FinishedOn" class="form-control" placeholder="Finished On" required>
                </div>
            </div>
            <div class="container-controls">
                <button class="btn btn-primary">Create</button>
            </div>
        </form>
    </div>
</div>
<script>
    $(function () {
        $("#finishedOn").datepicker();
    })
</script>

Gamayun.UI/Areas/Admin/Views/Semester/SemesterEdit.cshtml
@using Gamayun.Infrastucture.Command.Admin
@model EditSemesterCommandHandler.Command
@{
    ViewData["Title"] = "Edit Semester";
    var errors = ViewBag.Errors ?? Array.Empty<string>();
}

@await Html.PartialAsync("_PageHeader", "Semester Edit Page")

<hr />
<div class="container-fluid">
    <div class="jumbotron">
        @foreach (var error in errors)
        {
            <div class="alert alert-danger" role="alert">
                <strong>@error</strong>
            </div>
        }
        <form asp-area="Admin" asp-controller="Semester" asp-action="SemesterEdit">
            <input hidden asp-for="ID"/>
            <div class="row">
                <div class="col-lg-6 form-group">
                    <label asp-for="Major">Major</label>
                    <input asp-for="Major" class="form-control" placeholder="Major" required>
                </div>
                <div class="col-lg-6 form-group">
                    <label asp-for="FinishedOn">Finished On</label>
                    <input asp-for="FinishedOn" class="form-control" placeholder="Finished On" required>
                </div>
            </div>
            <div class="container-controls">
                <button class="btn btn-primary">Save</button>
            </div>
        </form>
    </div>
</div>
<script>
    $(function () {
        $("#finishedOn").datepicker();
    })
</script>

Gamayun.UI/Areas/Admin/Views/Semester/SemesterSearch.cshtml
@model IGridConfiguration
@{ 
    ViewData["Title"] = "Search Semesters";
}
@await Html.PartialAsync("_PageHeader", "Semester Search Page")

@await Html.PartialAsync("_Grid", Model)

Gamayun.UI/Areas/Admin/Views/Semester/SemesterView.cshtml
@model SemesterVm
@{ 
    ViewData["Title"] = "View Semester";
}
@await Html.PartialAsync("_PageHeader", "Semester View Page")

<hr />
<div class="container-fluid">
    <div class="jumbotron">
        <p><strong>Major:</strong>&nbsp;@Model.Major</p>
        <p><strong>Created on:</strong>&nbsp;@Model.CreatedOn</p>
        <p><strong>Ends on:</strong>&nbsp;@Model.FinishedOn</p>
        <p><strong>Status:</strong>&nbsp;@(Model.IsActive ? "Active" : "Not active")</p>
        @if (@Model.IsObsolete)
        {
            <div class="alert alert-danger">
                Semester is obsoleted
            </div>
        }
        <div class="container-controls">
            <a asp-action="SemesterEdit" asp-route-id="@Model.ID" class="btn btn-primary">Edit</a>
            @if (@Model.IsObsolete)
            {
                <form asp-action="SemesterRestore" asp-route-id="@Model.ID" method="post">
                    <button class="btn btn-success">Restore</button>
                </form>
            }
            else
            {
                <form asp-action="SemesterObsolete" asp-route-id="@Model.ID" method="post">
                    <button class="btn btn-danger">Obsolete</button>
                </form>
            }
        </div>
    </div>
</div>